name: Azure_DataFactory_Deploy
on:
  pull_request:
    paths:
      - ./kDevADF01
    branches: prod
  workflow_dispatch:
    
    
jobs:
  build:
#     runs-on: [self-hosted, Windows, X64]
    runs-on: windows-latest
    environment: Kagool-GitHub-01
      
    steps:
      - uses: actions/checkout@v1
      
      - name: Run Pre-deployment scripts
        shell: pwsh
        run: Install-Module -Name Az -Scope CurrentUser -Confirm
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KAGOOL_GITHUB_CREDENTIALS }}
          enable-AzPSSession: true 
          

      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: rg-kdevops-prod
          template: ./kDevADF01/ARMTemplateForFactory.json
          parameters: ./kDevADF01/ARMTemplateParametersForFactory.json factoryName=kProdADF01
