name: Azure_DataFactory_Deploy
on:
  push:
    branches: main
  workflow_dispatch:
    
    
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v1
      
      - name: Run Pre-deployment script
        shell: powershell
        run: Install-Module -Name Az -Scope CurrentUser -Confirm
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVOPS_SECRET_CREDENTIALS }}
          enable-AzPSSession: true 
          


#       - name: Deploy resources
#         uses: Azure/data-factory-deploy-action@v1.2.0
#         with:
#           resourceGroupName: rg-kdevops-prod
#           dataFactoryName: kProdADF01
#           armTemplateFile: './kDevADF01/ARMTemplateForFactory.json'
#           armTemplateParametersFile: './kDevADF01/ARMTemplateParametersForFactory.json'
#           #additionalParameters: 'key1=value key2=value keyN=value'
#           skipAzModuleInstallation: true
          
          
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: rg-kdevops-prod
          template: ./kDevADF01/ARMTemplateForFactory.json
          parameters: ./kDevADF01/ARMTemplateParametersForFactory.json factoryName=kProdADF01
